### ISSUE TITLE
enricher with kcg pipeline 

### ISSUE THREAD

**Issue by nitzan-tz** [netsampler/goflow2#74] opened 2022-03-01 21:20 UTC
I am trying to use the enricher with the flow-pipeline of kcg 
This is what I am doing (Almost sure it is not the best thing )
in the Dockerfile i am building the enricher and add it to the image
and I am running the following command

`./goflow2 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true  | ./enricher -transport.kafka.brokers=kafka:9092 -transport=kafka -transport.kafka.topic=flows -format=pb -format.protobuf.fixedlen=true -db.asn=/etc/clickhouse-server/GeoLite2-ASN.mmdb -db.country=/etc/clickhouse-server/GeoLite2-Country.mmdb `

But it looks like it is printing the output to STDOUT instead to send it to Kfaka (I don't see a connection in netstat )

**Comment by lspgn** [comment] 2022-03-14 05:37
Hello @nitzan-tz,
Apologies for the delay.
I was not able to reproduce. Could you give me more information about the version you're using?

**Comment by nitzan-tz** [comment] 2022-03-14 20:18
Hi, @lspgn 

I was able to work around it by using CMD in the docker file (Not sure if it is the best option ) 
CMD ./goflow2 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true  | ./enricher -transport.kafka.brokers=kafka:9092 -transport=kafka -transport.kafka.topic=flows -format=pb -format.protobuf.fixedlen=true -db.asn=/etc/clickhouse-server/GeoLite2-ASN.mmdb -db.country=/etc/clickhouse-server/GeoLite2-Country.mmdb

Another change was to map the proto file from the enreacher instead of the original one in the compose file

#      - ../../pb/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
      - ../../cmd/enricher/pb/flowext.proto:/var/lib/clickhouse/format_schemas/flow.proto

**Comment by lspgn** [comment] 2022-03-27 22:24
Hi @nitzan-tz,
What is the version/git commit of the repository you're building from?
`CMD` should be calling the shell. Have you tried
```
ENTRYPOINT [ "/bin/bash", "-c", "./goflow2 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true | ./enricher -transport.kafka.brokers=kafka:9092 -transport=kafka -transport.kafka.topic=flows -format=pb -format.protobuf.fixedlen=true -db.asn=/etc/clickhouse-server/GeoLite2-ASN.mmdb -db.country=/etc/clickhouse-server/GeoLite2-Country.mmdb"]
```

If I get this correctly:
* You edited the Dockerfile
* You added fields to the protobuf definition
I'm not sure what changes would you like to PR?

Note: if you're going to build more than a prototype, I would suggest to edit the `enricher` to consume from Kafka. You will simplify your stack.

**Comment by lspgn** [comment] 2022-04-29 03:55
Hello,
I haven't seen an update here, will close this. Feel free to reopen.

**Closed by lspgn** 2022-04-29 03:55 UTC
Labels: bug, question
